### ISSUE TITLE
Esempio di programma principale

### ISSUE THREAD

**Issue by iannellog** [ginevrabiagini/Progetto-Programmazione2024#1]
Prendete spunto dal seguente codice per organizzare la vostra applicazione.

    import pandas as pd
    from DataProcessing.data_processing import remove_duplicates, mancanti_fuori_range
    from DataProcessing.standardizer import Standardizer

    import sys

    # Caricare il file CSV
    dataset = sys.argv[1]
    #dataset = input("Inserisci il path del dataset: ")
    data = pd.read_csv(dataset)

    # Verifica e rimozione duplicati
    data = remove_duplicates(data)
    data = mancanti_fuori_range(data)

    standardizer = Standardizer()
    data_standardized, target = standardizer.standardize(data)

Ricordate nei file che importate di non iserire codice a livello 0, ma di inserirlo all'interno di frasi come:

    if __name__ == "__main__":

**Comment by ginevrabiagini** [comment]
codici aggiornati
