### ISSUE TITLE
correggere erroe nel main

### ISSUE THREAD

**Issue by iannellog** [ginevrabiagini/Progetto-Programmazione2024#2]
Nel file main.py avete scritto

    if _name_ == "_main_":

invece gli *underscore* ('_') devono essere due :

    if __name__ == "__main__":

Il programma va in errore. Fate più attenzione: prima di un commit e ancor più prima di un push fate sempre un test di esecuzione.

**Comment by ginevrabiagini** [comment]
Errore sistemato!
