### ISSUE TITLE
File data_processing.py

### ISSUE THREAD

**Issue by iannellog** [ginevrabiagini/Progetto-Programmazione2024#3]
Migliorate i commenti dei sottoprogrammi:

- anche se in tutti i casi i sottoprogrammi ricevono un dataframe e restituiscono un data frame, scrivetelo esplicitamente
- dove i sottoprogrammi stmpano qualcosa, scrivetelo (sintetricamente) nel commento: il commento devo permettere di capire cosa fa il sottoprogramma **anche senza leggere il codice del corpo**

Varificate se ci sono altre parti del vostro codice (non solo sottoprogrammi a se stante, ma anche classi e metodi) dove applicare questi suggerimenti

**Comment by simona2707** [comment]
Commenti aggiornati
