### ISSUE TITLE
File standardizer.py

### ISSUE THREAD

**Issue by iannellog** [ginevrabiagini/Progetto-Programmazione2024#6]
Chiederei di commentare il codice in modo uniforme: avete usato un metodo diverso per commentare i metodi rispetto a come avete commentato i sottoprogrammi nel file data_processing.py
Usate anche uno stile di codifica uniforme: non si capisce perché nel file data_processing.py avete introdotto dei sottoprogrammi e in standardizer invece avete introdotto una classe. Se decidete di usare sottoprogrammi separati allora usate sempre quelli; se viceversa volete ragiornare in termini di oggetti che svolgono funzioni allora uaate sempre classi con metodi
In altre parole è strano che nel mail i primi passi vengono svolti chiamando sottoprogrammi e poi si crea un oggetto per effettuare la standardizzazione: ci si aspett una certa unuformità nello stile di codifica perché questo migliora la leggibilità del codice

**Comment by ginevrabiagini** [comment]
codici aggiornati

**Comment by iannellog** [comment]
Bene l'introduzione di una classe per uniformità con il resto del codice, ma suggerisco di evitare di memorizzare il data frame come attributo dell'oggetto DataFrameCleaner e invece di passarlo come parametro di ingresso in tutti i metodi. In questo modo la semantica risulta più pulita perché nel codice attuale all'interno dell'oggetto resta un riferimento al data frame che però è accessibile anche esternamente. Naturalmente bisogna modificare di conseguenza il main e i commenti ai metodi.

**Comment by simona2707** [comment]
modifiche aggiornate
