### ISSUE TITLE
File model_development.py

### ISSUE THREAD

**Issue by iannellog** [ginevrabiagini/Progetto-Programmazione2024#7]
il codice del metodo fit andrebbe commentato riga per riga per spiegare cosa fa ciascuna linea di codice, altrimenti il tutto risulta molto criptico per chi non ha piena familiarità con i vari metodi chiamati.
Per esempio (ma è solo un esempio che va applicato anche al resto), non è scontato che che legge abvbia presente cosa viene restituito dal metodo *most_common* alla riga 56. Dal codice seguente deduco che dovrebbe essere una matrice (o una lista di liste) i cui elementi i cui elementi sono liste di coppie (tuple?), ma la cosa non è affatto scontata e in ogni caso non è semplice stabilire se il codice è corretto (lo sarà certamente, ma dovete mettervi nei panni di uno che non l'ha scritto e che vuole verificarlo)

**Comment by simona2707** [comment]
abbiamo aggiornato codice commentando riga per riga
