### ISSUE TITLE
Valutazione dei risultati

### ISSUE THREAD

**Issue by iannellog** [ginevrabiagini/Progetto-Programmazione2024#9]
Nel metoto evaluate, sia nella classe Holdout, suia nella classe KFoldCrossValidation, avete utilizzato esplicitamente i valorti delle label (2 e 4) per valutare la correttezza o meno della predizione. In questo modo il codice funziona solo se le label usate nel dataset hanno quei due valori.
Questo non è assolutamente necessario. 
Modificate quella parte di codice in modo da evitare di fare riferimento ai valori concreti delle label.

**Comment by simona2707** [comment]
codici aggiornati, insieme al main

**Comment by iannellog** [comment]
Nel metodo *evaluate* della classe *Holdout* manca in fondo l'istruzione:

    return output_metrics  # Restituisce le metriche calcolate

**Comment by ginevrabiagini** [comment]
E' già presente nel codice

**Comment by iannellog** [comment]
Hai ragione. Manca nella classe *KFoldCrossValidation*

**Comment by simona2707** [comment]
risolto
